# Generated by Django 5.0.6 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveSmallIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('max_amount_for_auto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('PERSONAL', 'Préstamo Personal'), ('COMMERCIAL', 'Préstamo Comercial'), ('MORTGAGE', 'Préstamo Hipotecario'), ('PRENDARIO', 'Préstamo Prendario'), ('MICROCREDIT', 'Microcrédito'), ('CREDIT_LINE', 'Línea de Crédito')], max_length=20)),
                ('interest_rate_type', models.CharField(choices=[('FIXED', 'Fija'), ('VARIABLE', 'Variable')], default='FIXED', max_length=10)),
                ('calculation_method', models.CharField(choices=[('SIMPLE', 'Interés Simple'), ('COMPOUND', 'Interés Compuesto')], default='SIMPLE', max_length=10)),
                ('payment_method', models.CharField(choices=[('NIVELADA', 'Cuotas Niveladas'), ('DECRECIENTE', 'Cuotas Decrecientes'), ('PERSONALIZADA', 'Cuotas Personalizadas')], default='NIVELADA', max_length=20)),
                ('annual_interest_rate', models.DecimalField(decimal_places=3, help_text='Tasa anual en %', max_digits=6)),
                ('late_fee_rate', models.DecimalField(decimal_places=3, default=0, help_text='Mora diaria en %', max_digits=6)),
                ('commission_rate', models.DecimalField(decimal_places=3, default=0, help_text='Comisión en %', max_digits=6)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_term_months', models.PositiveSmallIntegerField()),
                ('max_term_months', models.PositiveSmallIntegerField()),
                ('requires_guarantee', models.BooleanField(default=False)),
                ('requires_guarantor', models.BooleanField(default=False)),
                ('min_credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('approval_levels', models.PositiveSmallIntegerField(default=1)),
                ('auto_approve_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loan_number_prefix', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto Financiero',
                'verbose_name_plural': 'Productos Financieros',
            },
        ),
    ]
