# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('loan_products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflowstep',
            name='required_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_products', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstep',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='loan_products.loanproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowstep',
            unique_together={('product', 'step_order')},
        ),
    ]
