# Generated by Django 5.0.6 on 2026-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='payment_frequency',
            field=models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual')], default='MONTHLY', max_length=10),
        ),
    ]
