# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('INTERNAL', 'Interna')], max_length=10)),
                ('event_type', models.CharField(choices=[('PAYMENT_DUE', 'Cuota por Vencer'), ('PAYMENT_OVERDUE', 'Cuota Vencida'), ('LOAN_APPROVED', 'Préstamo Aprobado'), ('LOAN_REJECTED', 'Préstamo Rechazado'), ('LOAN_DISBURSED', 'Préstamo Desembolsado'), ('PAYMENT_RECEIVED', 'Pago Recibido'), ('LOAN_COMPLETED', 'Préstamo Completado'), ('ACCOUNT_CREATED', 'Cuenta Creada'), ('PASSWORD_RESET', 'Restablecimiento de Contraseña'), ('CUSTOM', 'Personalizado')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(help_text='Plantilla Jinja2. Variables: {{customer_name}}, {{loan_number}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('send_days_before', models.PositiveSmallIntegerField(blank=True, help_text='Días antes del vencimiento para enviar', null=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=10)),
                ('recipient_address', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviada'), ('FAILED', 'Fallida'), ('READ', 'Leída')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_id', models.CharField(blank=True, max_length=50)),
                ('recipient_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Notificación',
                'ordering': ['-created_at'],
            },
        ),
    ]
