# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0002_initial'),
        ('loan_products', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_products.loanproduct'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.commissionrule'),
        ),
    ]
