# Generated by Django 5.0.6 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('CALL', 'Llamada Telefónica'), ('VISIT', 'Visita Domiciliar'), ('NOTICE', 'Notificación Escrita'), ('LEGAL', 'Acción Legal'), ('AGREEMENT', 'Acuerdo de Pago'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('notes', models.TextField()),
                ('result', models.CharField(blank=True, choices=[('CONTACT_MADE', 'Contacto Realizado'), ('NO_CONTACT', 'Sin Contacto'), ('PROMISE_TO_PAY', 'Promesa de Pago'), ('REFUSED', 'Negativa de Pago'), ('AGREEMENT_REACHED', 'Acuerdo Alcanzado'), ('PARTIAL_PAYMENT', 'Pago Parcial')], max_length=25)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('next_action_type', models.CharField(blank=True, choices=[('CALL', 'Llamada Telefónica'), ('VISIT', 'Visita Domiciliar'), ('NOTICE', 'Notificación Escrita'), ('LEGAL', 'Acción Legal'), ('AGREEMENT', 'Acuerdo de Pago'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('days_past_due_at_action', models.PositiveSmallIntegerField(default=0)),
                ('amount_owed_at_action', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Acción de Cobro',
                'verbose_name_plural': 'Acciones de Cobro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('agreed_payment_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FULFILLED', 'Cumplido'), ('BROKEN', 'Incumplido'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Acuerdo de Pago',
                'verbose_name_plural': 'Acuerdos de Pago',
            },
        ),
    ]
