# Generated by Django 5.0.6 on 2026-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='action_type',
            field=models.CharField(choices=[('CALL', 'Llamada Telefónica'), ('VISIT', 'Visita Domiciliar'), ('NOTICE', 'Notificación Escrita'), ('EMAIL', 'Correo Electrónico'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('AGREEMENT', 'Acuerdo de Pago'), ('LEGAL', 'Acción Legal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='next_action_type',
            field=models.CharField(blank=True, choices=[('CALL', 'Llamada Telefónica'), ('VISIT', 'Visita Domiciliar'), ('NOTICE', 'Notificación Escrita'), ('EMAIL', 'Correo Electrónico'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('AGREEMENT', 'Acuerdo de Pago'), ('LEGAL', 'Acción Legal')], max_length=20),
        ),
    ]
