# Generated by Django 5.0.6 on 2026-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0005_alter_collectionaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaction',
            name='address_visited',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
