# Generated by Django 5.0.6 on 2026-06-13 20:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('customers', 'Clientes'), ('loan_applications', 'Solicitudes'), ('loans', 'Préstamos'), ('payments', 'Cobros'), ('cash', 'Caja'), ('collections', 'Cobranza'), ('guarantees', 'Garantías'), ('accounting', 'Contabilidad'), ('reports', 'Reportes'), ('contracts', 'Contratos'), ('documents', 'Documentos'), ('commissions', 'Comisiones'), ('legal', 'Legal'), ('users', 'Usuarios'), ('branches', 'Sucursales'), ('config', 'Configuración'), ('audit', 'Auditoría'), ('currency_exchange', 'Cambio de Divisas'), ('investors', 'Inversionistas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', validators=[apps.core.validators.validate_image_extension, apps.core.validators.validate_image_size]),
        ),
    ]
