# Generated by Django 5.0.6 on 2026-06-03 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('MANUAL', 'Solo Manual')], default='DAILY', max_length=10)),
                ('time_of_day', models.TimeField(default='02:00', help_text='Hora del día (24h)')),
                ('retention_days', models.PositiveSmallIntegerField(default=30, help_text='Días que se conservan los backups antes de eliminarse')),
                ('notify_emails', models.TextField(blank=True, help_text='Correos a notificar (uno por línea)')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración de Backup',
                'verbose_name_plural': 'Configuración de Backup',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='IN_PROGRESS', max_length=15)),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Programado')], default='MANUAL', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='CredCore', max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Razón Social')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='RNC / NIT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='República Dominicana', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Número WhatsApp Business', max_length=20)),
                ('bank_accounts', models.TextField(blank=True, help_text='Cuentas para recibir transferencias')),
                ('currency', models.CharField(default='DOP', max_length=3)),
                ('currency_symbol', models.CharField(default='RD$', max_length=5)),
                ('timezone', models.CharField(default='America/Santo_Domingo', max_length=50)),
                ('receipt_footer', models.TextField(blank=True, default='¡Gracias por su preferencia!')),
                ('statement_footer', models.TextField(blank=True, default='Documento generado automáticamente.')),
                ('legal_notice', models.TextField(blank=True, help_text='Aviso legal en contratos')),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
