# Generated by Django 5.0.6 on 2026-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tasa de cambio: 1 USD = X DOP', max_digits=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='license_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='license_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='license_plan',
            field=models.CharField(choices=[('TRIAL', 'Prueba (30 días)'), ('BASIC', 'Básico (1 sucursal)'), ('PROFESSIONAL', 'Profesional (3 sucursales)'), ('ENTERPRISE', 'Empresarial (ilimitado)')], default='TRIAL', max_length=15),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='max_branches',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='secondary_currency',
            field=models.CharField(blank=True, default='USD', help_text='Moneda secundaria', max_length=3),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='secondary_currency_symbol',
            field=models.CharField(blank=True, default='US$', max_length=5),
        ),
    ]
