# Generated by Django 5.0.6 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lista Negra',
            },
        ),
        migrations.CreateModel(
            name='CreditEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.PositiveSmallIntegerField()),
                ('risk_level', models.CharField(max_length=10)),
                ('evaluation_details', models.JSONField(default=dict)),
                ('recommendation', models.TextField(blank=True)),
                ('evaluated_by', models.CharField(default='SYSTEM', max_length=50)),
            ],
            options={
                'verbose_name': 'Evaluación Crediticia',
                'verbose_name_plural': 'Evaluaciones Crediticias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('field', models.CharField(choices=[('monthly_income', 'Ingresos Mensuales'), ('employment_years', 'Antigüedad Laboral'), ('debt_to_income_ratio', 'Relación Deuda/Ingreso'), ('active_loans_count', 'Préstamos Activos'), ('payment_on_time_rate', 'Tasa de Pago a Tiempo'), ('max_days_past_due', 'Máximo Días en Mora'), ('completed_loans', 'Préstamos Completados')], max_length=50)),
                ('condition', models.CharField(choices=[('gt', 'Mayor que'), ('gte', 'Mayor o igual que'), ('lt', 'Menor que'), ('lte', 'Menor o igual que'), ('eq', 'Igual a'), ('between', 'Entre')], max_length=10)),
                ('value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('score_points', models.SmallIntegerField(help_text='Positivo suma, negativo resta')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Scoring',
                'verbose_name_plural': 'Reglas de Scoring',
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('min_score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveSmallIntegerField()),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['min_score'],
            },
        ),
    ]
