# Generated by Django 5.0.6 on 2026-06-09 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('cash', '0002_initial'),
        ('customers', '0004_alter_customer_photo_alter_customerdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('buy_rate', models.DecimalField(decimal_places=4, help_text='Precio al que COMPRAMOS dólares (pagamos DOP por cada USD)', max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, help_text='Precio al que VENDEMOS dólares (cobramos DOP por cada USD)', max_digits=10)),
                ('reference_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa referencia Banco Central RD', max_digits=10, null=True)),
                ('spread', models.DecimalField(decimal_places=4, default=0, help_text='Diferencia entre venta y compra (ganancia por USD)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('BUY', 'Compra de USD'), ('SELL', 'Venta de USD')], db_index=True, max_length=4)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completada'), ('CANCELLED', 'Anulada'), ('PENDING', 'Pendiente')], db_index=True, default='COMPLETED', max_length=10)),
                ('rate_applied', models.DecimalField(decimal_places=4, help_text='Tasa efectiva aplicada en esta operación', max_digits=10)),
                ('usd_amount', models.DecimalField(decimal_places=2, help_text='Cantidad en dólares (USD)', max_digits=15)),
                ('dop_amount', models.DecimalField(decimal_places=2, help_text='Cantidad en pesos dominicanos (DOP)', max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, help_text='Ganancia de la operación en DOP', max_digits=15)),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente (si no está registrado)', max_length=200)),
                ('customer_id_number', models.CharField(blank=True, help_text='Cédula/Pasaporte (requerido por ley para montos >= US$500)', max_length=30)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque')], default='CASH', max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='No. de referencia/cheque', max_length=100)),
                ('receipt_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_transactions', to='branches.branch')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_transactions', to='cash.cashsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_transactions', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_operations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='currency_exchange.exchangerate')),
            ],
            options={
                'verbose_name': 'Transacción de Cambio',
                'verbose_name_plural': 'Transacciones de Cambio',
                'ordering': ['-created_at'],
            },
        ),
    ]
