# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
