# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('loan_applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_principal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_late_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Pago Parcial'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida'), ('WAIVED', 'Condonada')], db_index=True, default='PENDING', max_length=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('loan_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_interest_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('payment_method', models.CharField(choices=[('NIVELADA', 'Cuotas Niveladas'), ('DECRECIENTE', 'Cuotas Decrecientes'), ('PERSONALIZADA', 'Cuotas Personalizadas')], max_length=20)),
                ('late_fee_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_to_pay', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_late_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('COMPLETED', 'Completado'), ('DEFAULTED', 'En Mora'), ('WRITTEN_OFF', 'Castigado'), ('CANCELLED', 'Cancelado'), ('REFINANCED', 'Refinanciado')], db_index=True, default='ACTIVE', max_length=15)),
                ('days_past_due', models.PositiveSmallIntegerField(default=0)),
                ('installments_paid', models.PositiveSmallIntegerField(default=0)),
                ('installments_remaining', models.PositiveSmallIntegerField(default=0)),
                ('disbursement_date', models.DateField()),
                ('first_payment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_refinanced', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loan_applications.loanapplication')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-created_at'],
            },
        ),
    ]
