# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('loan_products', '0002_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='original_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinanced_loans', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan_products.loanproduct'),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'branch'], name='loans_loan_status_8505ae_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer', 'status'], name='loans_loan_custome_9efb67_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['days_past_due'], name='loans_loan_days_pa_4cd8ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanschedule',
            unique_together={('loan', 'installment_number')},
        ),
    ]
