# Generated by Django 5.0.6 on 2026-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='first_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_method',
            field=models.CharField(choices=[('NIVELADA', 'Cuotas Niveladas'), ('DECRECIENTE', 'Cuotas Decrecientes'), ('PERSONALIZADA', 'Cuotas Personalizadas')], default='NIVELADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
