# Generated by Django 5.0.6 on 2026-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_first_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_type',
            field=models.CharField(choices=[('SIMPLE', 'Interés Simple'), ('COMPOUND', 'Interés Compuesto')], default='SIMPLE', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_frequency',
            field=models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('CUSTOM', 'Personalizado')], default='MONTHLY', max_length=10),
        ),
    ]
