# Generated by Django 5.0.6 on 2026-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_interest_type_loan_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='client_signature',
            field=models.TextField(blank=True, help_text='Firma digital del cliente en formato base64 PNG'),
        ),
        migrations.AddField(
            model_name='loan',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='signature_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
