# Generated by Django 5.0.6 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='DOP', max_length=3)),
                ('currency_symbol', models.CharField(default='RD$', max_length=5)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('loan_number_prefix', models.CharField(default='PRES', max_length=10)),
                ('client_number_prefix', models.CharField(default='CLI', max_length=10)),
                ('receipt_number_prefix', models.CharField(default='REC', max_length=10)),
                ('working_hours_start', models.TimeField(default='08:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
            ],
        ),
    ]
