# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='branches.branch'),
        ),
    ]
