# Generated by Django 5.0.6 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automático')], max_length=15)),
                ('storage', models.CharField(choices=[('LOCAL', 'Local'), ('CLOUD', 'Nube'), ('SHARED', 'Carpeta Compartida')], default='LOCAL', max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('DELETED', 'Eliminado')], default='IN_PROGRESS', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-created_at'],
            },
        ),
    ]
