# Generated by Django 5.0.6 on 2026-06-02 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='NATURAL', max_length=10)),
                ('customer_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('second_last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_type', models.CharField(blank=True, max_length=100)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('id_type', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASSPORT', 'Pasaporte'), ('RNC', 'RNC'), ('OTHER', 'Otro')], default='CEDULA', max_length=10)),
                ('id_number', models.CharField(db_index=True, max_length=20)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='República Dominicana', max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('employer_phone', models.CharField(blank=True, max_length=20)),
                ('employer_address', models.TextField(blank=True)),
                ('employment_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLOCKED', 'Bloqueado')], db_index=True, default='ACTIVE', max_length=10)),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='LOW', max_length=10)),
                ('credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('total_loans_count', models.PositiveIntegerField(default=0)),
                ('active_loans_count', models.PositiveIntegerField(default=0)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CEDULA_FRONT', 'Cédula (Frente)'), ('CEDULA_BACK', 'Cédula (Reverso)'), ('PASSPORT', 'Pasaporte'), ('RNC', 'RNC'), ('INCOME_PROOF', 'Comprobante de Ingresos'), ('BANK_STATEMENT', 'Estado de Cuenta'), ('ADDRESS_PROOF', 'Comprobante de Domicilio'), ('LABOR_CERT', 'Certificación Laboral'), ('TAX_RETURN', 'Declaración de Impuestos'), ('OTHER', 'Otro')], max_length=30)),
                ('file', models.FileField(upload_to='customers/documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_late_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_loans', models.PositiveSmallIntegerField(default=0)),
                ('completed_loans', models.PositiveSmallIntegerField(default=0)),
                ('defaulted_loans', models.PositiveSmallIntegerField(default=0)),
                ('payment_on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_days_past_due', models.PositiveSmallIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('FAMILY', 'Familiar'), ('FRIEND', 'Amigo'), ('COLLEAGUE', 'Compañero de Trabajo'), ('NEIGHBOR', 'Vecino'), ('OTHER', 'Otro')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
