# Generated by Django 5.0.6 on 2026-06-02 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, default='Dominicano/a', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/photos/'),
        ),
        migrations.AddField(
            model_name='customerfinancialsummary',
            name='next_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='customerfinancialsummary',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfinancialsummary',
            name='total_late_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Soltero/a'), ('MARRIED', 'Casado/a'), ('DIVORCED', 'Divorciado/a'), ('WIDOWED', 'Viudo/a'), ('UNION', 'Unión Libre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='document_type',
            field=models.CharField(choices=[('CEDULA_FRONT', 'Cédula (Frente)'), ('CEDULA_BACK', 'Cédula (Reverso)'), ('PASSPORT', 'Pasaporte'), ('RNC', 'RNC'), ('INCOME_PROOF', 'Comprobante de Ingresos'), ('BANK_STATEMENT', 'Estado de Cuenta'), ('ADDRESS_PROOF', 'Comprobante de Domicilio'), ('LABOR_CERT', 'Certificación Laboral'), ('SALARY_CERT', 'Certificación Salarial'), ('TAX_RETURN', 'Declaración de Impuestos'), ('VEHICLE_TITLE', 'Título de Vehículo'), ('PROPERTY_TITLE', 'Título de Propiedad'), ('PHOTO', 'Fotografía'), ('SIGNED_FORM', 'Formulario Firmado'), ('OTHER', 'Otro')], max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CALL', 'Llamada'), ('VISIT', 'Visita'), ('MEETING', 'Reunión'), ('NOTE', 'Nota Interna'), ('ALERT', 'Alerta')], max_length=20)),
                ('date', models.DateTimeField()),
                ('result', models.CharField(blank=True, choices=[('POSITIVE', 'Positivo'), ('NEGATIVE', 'Negativo'), ('PENDING', 'Pendiente'), ('NO_ANSWER', 'Sin respuesta')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBankReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Ahorros'), ('CHECKING', 'Corriente'), ('CREDIT', 'Crédito'), ('OTHER', 'Otro')], max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_references', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('activity_type', models.CharField(blank=True, max_length=200)),
                ('years_operating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('address', models.TextField(blank=True)),
                ('rnc', models.CharField(blank=True, max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCommercialReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('relationship_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_references', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCreditEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.CharField(blank=True, choices=[('EXCELLENT', 'Excelente'), ('GOOD', 'Bueno'), ('REGULAR', 'Regular'), ('RISKY', 'Riesgoso')], max_length=20)),
                ('age_score', models.SmallIntegerField(default=0)),
                ('income_score', models.SmallIntegerField(default=0)),
                ('employment_score', models.SmallIntegerField(default=0)),
                ('payment_history_score', models.SmallIntegerField(default=0)),
                ('debt_score', models.SmallIntegerField(default=0)),
                ('guarantees_score', models.SmallIntegerField(default=0)),
                ('recommended_max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_evaluations', to='customers.customer')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('INDEFINITE', 'Indefinido'), ('FIXED', 'Plazo Fijo'), ('TEMPORARY', 'Temporal'), ('PART_TIME', 'Medio Tiempo')], max_length=20)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_address', models.TextField(blank=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=200)),
                ('supervisor_phone', models.CharField(blank=True, max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('business_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('housing_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('food_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('services_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('education_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_loans_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_card_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_installments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='customers.customer')),
            ],
        ),
    ]
