# Generated by Django 5.0.6 on 2026-06-09 15:19

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_address_reference_customer_id_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/photos/', validators=[apps.core.validators.validate_image_extension, apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='file',
            field=models.FileField(upload_to='customers/documents/%Y/%m/', validators=[apps.core.validators.validate_file_extension, apps.core.validators.validate_file_size]),
        ),
    ]
