# Generated by Django 5.0.6 on 2026-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_photo_alter_customerdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
