# Generated by Django 5.0.6 on 2026-06-02 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guarantee_type', models.CharField(choices=[('VEHICLE', 'Vehículo'), ('REAL_ESTATE', 'Inmueble'), ('EQUIPMENT', 'Equipo'), ('INVENTORY', 'Inventario'), ('OTHER', 'Otro')], max_length=20)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('appraisal_date', models.DateField(blank=True, null=True)),
                ('appraiser', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('RELEASED', 'Liberada'), ('FORECLOSED', 'Ejecutada')], default='ACTIVE', max_length=15)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='guarantees/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('HOUSE', 'Casa'), ('APARTMENT', 'Apartamento'), ('LAND', 'Terreno'), ('COMMERCIAL', 'Local Comercial'), ('OTHER', 'Otro')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('title_number', models.CharField(blank=True, max_length=100)),
                ('registry', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
