# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('guarantees', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guaranteedocument',
            name='guarantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guarantees.guarantee'),
        ),
        migrations.AddField(
            model_name='guaranteedocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestateguarantee',
            name='guarantee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate', to='guarantees.guarantee'),
        ),
        migrations.AddField(
            model_name='vehicleguarantee',
            name='guarantee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='guarantees.guarantee'),
        ),
    ]
