# Generated by Django 5.0.6 on 2026-06-10 19:12

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guarantee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Garantía', 'verbose_name_plural': 'Garantías'},
        ),
        migrations.AlterField(
            model_name='guaranteedocument',
            name='file',
            field=models.FileField(upload_to='guarantees/documents/%Y/%m/', validators=[apps.core.validators.validate_file_extension, apps.core.validators.validate_file_size]),
        ),
    ]
