# Generated by Django 5.0.6 on 2026-06-02 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_type', models.CharField(choices=[('REGULAR', 'Pago Regular'), ('PARTIAL', 'Pago Parcial'), ('EXTRAORDINARY', 'Abono Extraordinario'), ('FULL_PAYMENT', 'Cancelación Total'), ('LATE_FEE', 'Pago de Mora')], max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque'), ('CARD', 'Tarjeta'), ('OTHER', 'Otro')], default='CASH', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('REVERSED', 'Revertido')], default='CONFIRMED', max_length=10)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cash.cashsession')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
