# Generated by Django 5.0.6 on 2026-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque'), ('CARD', 'Tarjeta'), ('DEPOSIT', 'Depósito Bancario'), ('DIGITAL_WALLET', 'Billetera Digital'), ('OTHER', 'Otro')], default='CASH', max_length=20),
        ),
    ]
