# Generated by Django 5.0.6 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('DEMAND', 'Demanda'), ('EMBARGO', 'Embargo'), ('EXECUTION', 'Ejecución'), ('OTHER', 'Otro')], max_length=20)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('court', models.CharField(blank=True, max_length=200)),
                ('attorney', models.CharField(blank=True, max_length=200)),
                ('attorney_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Proceso'), ('WON', 'Ganado'), ('LOST', 'Perdido'), ('SETTLED', 'Acordado'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=15)),
                ('filed_at', models.DateField(blank=True, null=True)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Caso Legal',
                'verbose_name_plural': 'Casos Legales',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='legal/documents/%Y/%m/')),
                ('document_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
