# Generated by Django 5.0.6 on 2026-06-02 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='applications/documents/%Y/%m/')),
                ('is_required', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('action', models.CharField(choices=[('SUBMITTED', 'Enviada'), ('APPROVED_STEP', 'Paso Aprobado'), ('REJECTED', 'Rechazada'), ('RETURNED', 'Devuelta'), ('ESCALATED', 'Escalada'), ('CANCELLED', 'Cancelada'), ('DISBURSED', 'Desembolsada')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('requested_term_months', models.PositiveSmallIntegerField()),
                ('purpose', models.TextField(verbose_name='Propósito del préstamo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada'), ('UNDER_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada'), ('DISBURSED', 'Desembolsada')], db_index=True, default='DRAFT', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('monthly_payment_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debt_to_income_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_score_at_application', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('approved_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamo',
                'ordering': ['-created_at'],
            },
        ),
    ]
