# Generated by Django 5.0.6 on 2026-06-13 20:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to='applications/documents/%Y/%m/', validators=[apps.core.validators.validate_file_extension, apps.core.validators.validate_file_size]),
        ),
    ]
