# Generated by Django 5.0.6 on 2026-06-02 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('content', models.TextField(help_text='HTML renderizado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/pdfs/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_SIGNATURE', 'Pendiente de Firma'), ('SIGNED', 'Firmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_type', models.CharField(choices=[('BORROWER', 'Prestatario'), ('GUARANTOR', 'Garante'), ('OFFICER', 'Oficial'), ('WITNESS', 'Testigo')], max_length=15)),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_id_number', models.CharField(max_length=20)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 de la firma digital')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('LOAN', 'Contrato de Préstamo'), ('PAGARE', 'Pagaré'), ('COMMITMENT', 'Carta de Compromiso'), ('REFINANCING', 'Acuerdo de Refinanciamiento'), ('MORA_AGREEMENT', 'Acuerdo de Mora'), ('GUARANTEE', 'Contrato de Garantía')], max_length=20)),
                ('content', models.TextField(help_text='Plantilla HTML con variables Jinja2')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
            },
        ),
    ]
